### ISSUE TITLE
needs_dots error

### ISSUE THREAD

**Issue by f00baroo** [nacnudus/unpivotr#43] opened 2021-02-09 06:43 UTC
When using this file (link goes to the German Statistical Agency)
https://www.destatis.de/DE/Themen/Laender-Regionen/Regionales/Gemeindeverzeichnis/Administrativ/Archiv/GVAuszugQ/AuszugGV4QAktuell.xlsx?__blob=publicationFile

and running the following code https://pastebin.com/7CZSD1fU

I get an error /warning

*(Warnmeldung means Warning)*
```
Warnmeldung:
`...` is not empty.

We detected these problematic arguments:
*  `needs_dots`

These dots only exist to allow future extensions and should be empty.
Did you misspecify an argument? 
```

It **seems** to not interfere with running the program, but it surely is confusing 

Edit: Adding R session info (unfortunately, my company uses Microsoft R Open, so some things are not up to date...)

R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252
[4] LC_NUMERIC=C                    LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] unpivotr_0.6.0       tidyxl_1.0.6         janitor_2.0.1        readxl_1.3.1         forcats_0.5.0       
 [6] stringr_1.4.0        dplyr_1.0.0          purrr_0.3.4          readr_1.3.1          tidyr_1.1.0         
[11] tibble_3.0.2         ggplot2_3.3.2        tidyverse_1.3.0      RevoUtils_11.0.2     RevoUtilsMath_11.0.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5       cellranger_1.1.0 pillar_1.4.6     compiler_4.0.2   dbplyr_1.4.4     tools_4.0.2     
 [7] jsonlite_1.7.0   lubridate_1.7.9  lifecycle_0.2.0  gtable_0.3.0     pkgconfig_2.0.3  rlang_0.4.6     
[13] reprex_0.3.0     cli_2.0.2        DBI_1.1.0        rstudioapi_0.11  haven_2.3.1      withr_2.2.0     
[19] xml2_1.3.2       httr_1.4.1       fs_1.4.2         generics_0.0.2   vctrs_0.3.1      hms_0.5.3       
[25] grid_4.0.2       tidyselect_1.1.0 snakecase_0.11.0 glue_1.4.1       R6_2.3.0         fansi_0.4.1     
[31] modelr_0.1.8     blob_1.2.1       magrittr_1.5     backports_1.1.7  scales_1.1.1     ellipsis_0.3.1  
[37] rvest_0.3.5      assertthat_0.2.1 colorspace_1.4-1 utf8_1.1.4       stringi_1.4.6    munsell_0.5.0   
[43] broom_0.7.0      crayon_1.3.4

**Comment by nacnudus** [comment] 2021-02-12 17:48
Thanks for reporting this.  I have transferred it to unpivotr, because the problem almost certainly occurs when `behead()` is called.  Please could you confirm that?

I can't reproduce the problem.  I haven't tried installing all the same versions of packages as you have.  Looking at them, they don't seem drastically out of date.  Here are mine.

```txt
#  package     * version    date       lib source                            
#  assertthat    0.2.1      2019-03-21 [1] CRAN (R 4.0.0)                    
#  cachem        1.0.3      2021-02-04 [1] CRAN (R 4.0.3)                    
#  callr         3.5.1      2020-10-13 [1] CRAN (R 4.0.3)                    
#  cli           2.3.0      2021-01-31 [1] CRAN (R 4.0.3)                    
#  colorout    * 1.2-2      2020-04-27 [1] Github (jalvesaq/colorout@726d681)
#  crayon        1.4.1      2021-02-08 [1] CRAN (R 4.0.3)                    
#  DBI           1.1.1      2021-01-15 [1] CRAN (R 4.0.3)                    
#  desc          1.2.0      2018-05-01 [1] CRAN (R 4.0.0)                    
#  devtools    * 2.3.2      2020-09-18 [1] CRAN (R 4.0.2)                    
#  dplyr         1.0.4.9000 2021-02-12 [1] Github (tidyverse/dplyr@4e7a464)  
#  ellipsis      0.3.1      2020-05-15 [1] CRAN (R 4.0.2)                    
#  fastmap       1.1.0      2021-01-25 [1] CRAN (R 4.0.3)                    
#  fs            1.5.0      2020-07-31 [1] CRAN (R 4.0.2)                    
#  generics      0.1.0      2020-10-31 [1] CRAN (R 4.0.3)                    
#  glue          1.4.2      2020-08-27 [1] CRAN (R 4.0.2)                    
#  lifecycle     0.2.0      2020-03-06 [1] CRAN (R 4.0.0)                    
#  magrittr      2.0.1      2020-11-17 [1] CRAN (R 4.0.3)                    
#  memoise       2.0.0      2021-01-26 [1] CRAN (R 4.0.3)                    
#  nvimcom     * 0.9-105    2021-01-14 [1] local                             
#  pillar        1.4.7      2020-11-20 [1] CRAN (R 4.0.3)                    
#  pkgbuild      1.2.0      2020-12-15 [1] CRAN (R 4.0.3)                    
#  pkgconfig     2.0.3      2019-09-22 [1] CRAN (R 4.0.0)                    
#  pkgload       1.1.0      2020-05-29 [1] CRAN (R 4.0.2)                    
#  prettyunits   1.1.1      2020-01-24 [1] CRAN (R 4.0.0)                    
#  processx      3.4.5      2020-11-30 [1] CRAN (R 4.0.3)                    
#  ps            1.5.0      2020-12-05 [1] CRAN (R 4.0.3)                    
#  purrr         0.3.4      2020-04-17 [1] CRAN (R 4.0.0)                    
#  R6            2.5.0      2020-10-28 [1] CRAN (R 4.0.3)                    
#  Rcpp          1.0.6      2021-01-15 [1] CRAN (R 4.0.3)                    
#  remotes       2.2.0      2020-07-21 [1] CRAN (R 4.0.2)                    
#  rlang         0.4.10     2020-12-30 [1] CRAN (R 4.0.3)                    
#  rprojroot     2.0.2      2020-11-15 [1] CRAN (R 4.0.3)                    
#  sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 4.0.0)                    
#  testthat      3.0.1      2020-12-17 [1] CRAN (R 4.0.3)                    
#  tibble        3.0.6      2021-01-29 [1] CRAN (R 4.0.3)                    
#  tidyr         1.1.2      2020-08-27 [1] CRAN (R 4.0.2)                    
#  tidyselect    1.1.0      2020-05-11 [1] CRAN (R 4.0.2)                    
#  tidyxl      * 1.0.7      2020-11-16 [1] CRAN (R 4.0.3)                    
#  unpivotr    * 0.6.1      2020-08-03 [1] CRAN (R 4.0.2)                    
#  usethis     * 2.0.1      2021-02-10 [1] CRAN (R 4.0.3)                    
#  vctrs         0.3.6      2020-12-17 [1] CRAN (R 4.0.3)                    
#  withr         2.4.1      2021-01-26 [1] CRAN (R 4.0.3)                    
```

**Comment by nacnudus** [comment] 2021-02-17 13:21
Closing because I can't reproduce the problem, and it's probably a package version problem.  Feel free to reopen if the warning becomes an error, or a way is found to reproduce it reliably.

**Closed by nacnudus** 2021-02-17 13:21 UTC
